import './jsx'
import './ok-person'
import './ok-person-group'
import './ok-person-card'
import './ok-person-detail'
import './ok-popover'
import './ok-overlay-wrap'
import './ok-person-select'
import './ok-person-select/ok-ant-person-select'
import './ok-department-search/ok-ant-department-search.ts'
import './ok-accessory/ok-upload-drag/ok-upload-drag'
import './ok-accessory/ok-upload-list/ok-upload-list'
import './ok-accessory/ok-upload-subtable/ok-upload-subtable-file'
import './ok-accessory/ok-upload-subtable/ok-upload-subtable-image'
// import './ok-accessory/ok-upload-dragger'
// import './ok-accessory/ok-upload-dragger-vue'
import './ok-accessory/ok-upload-drag/ok-file-list'
import './ok-accessory/ok-upload-list/ok-file-table'
// import './ok-accessory/ok-progress'
import './ok-accessory/ok-progress-vue'
import './ok-accessory/ok-upload-image/ok-file-image'
import './ok-accessory/ok-upload-image/ok-upload-image'
import './ok-accessory/ok-file-icon'
import './ok-tooltip'
import './ok-button'
// import './ok-attachment/ok-attachment-drag'
import './lang'
import './ok-person-cell'
import './ok-avatar'
import './ok-employee-select'
import './ok-employee-select/ok-employee-input'
import './ok-employee-select/ok-employee-tree'
import './ok-department-select'
import './ok-department-select/ok-department-input'
import './ok-department-select/ok-department-tree'
import './ok-department-select/ok-department-more'
