// @ts-ignore
import 'vue/dist/vue.cjs.prod.js'
import './lang'
import './jsx'
// 人员卡片
import './ok-avatar'
import './ok-person-card'
import './ok-person-cell'
import './ok-person-group'
// 上传
import './ok-accessory/ok-upload-drag/ok-upload-drag'
import './ok-accessory/ok-upload-list/ok-upload-list'
import './ok-accessory/ok-upload-subtable/ok-upload-subtable-file'
import './ok-accessory/ok-upload-subtable/ok-upload-subtable-image'
import './ok-accessory/ok-upload-drag/ok-file-list'
import './ok-accessory/ok-upload-list/ok-file-table'
import './ok-accessory/ok-progress-vue'
import './ok-accessory/ok-upload-image/ok-file-image'
import './ok-accessory/ok-upload-image/ok-upload-image'
import './ok-accessory/ok-file-icon'
// 人员选择
import './ok-employee-select'
// import './ok-employee-select/ok-employee-input'
// import './ok-employee-select/ok-employee-tree'
// 部门选择
import './ok-department-select'
import './ok-department-select/ok-department-input'
import './ok-department-select/ok-department-tree'
import './ok-department-select/ok-department-more'
// import './ok-tooltip'
